collections:
  sections:
    output: true

plugins:
  - jekyll-target-blank

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"

